### PR TITLE
Add API for creating embeddings

### PR DESCRIPTION
**Pull request by nstiurca**

### CODE REVIEW

**Comment by nstiurca** [comment]
Looks like API key isn't working as expected, hence the failures. Tests did pass locally FWIW.

**Comment by nstiurca** [comment]
Local test run: [testOpenAI.jl.txt](https://github.com/rory-linehan/OpenAI.jl/files/10876026/testOpenAI.jl.txt)


```
julia -e 'using Pkg; Pkg.test("OpenAI")' 2>&1 | tee /tmp/testOpenAI.jl.txt
     Testing OpenAI
      Status `/tmp/jl_BLIfDh/Project.toml`
  [0f8b85d8] JSON3 v1.12.0
  [e9f21f70] OpenAI v0.5.1 `~/.julia/dev/OpenAI`
  [f43a241f] Downloads v1.6.0 `@stdlib/Downloads`
  [8dfed614] Test `@stdlib/Test`

< SNIP >

Test Summary: | Pass  Total  Time
OpenAI.jl     |   20     20  6.4s
     Testing OpenAI tests passed 
```

**Comment by rory-linehan** [comment]
Yes, unfortunately the CI tests don't work with forks because the actions secret isn't present. Thanks for the PR!

**Comment by nstiurca** [comment]
Interesting, I don't think I had that problem with my last PR. I wonder what's different. Anyways, thanks for the quick merge again!

**Pull request merged**
