### PR TITLE
Removed Manifest.toml & updated compat

### PR DESCRIPTION
**Pull request by gnadt**

### CODE REVIEW

**Comment by gnadt** [comment]
Not completely sure, but I think the tests fail because `OPENAI_API_KEY` isn't set for my fork

**Comment by rory-linehan** [comment]
Yeah, that's definitely what's happening. Kind of a bummer, I'll have to figure out a different way to do CI.

**Review by rory-linehan — APPROVED** [review]

**Comment by gnadt** [comment]
Yeah it does work if I add my `OPENAI_API_KEY` as a repository secret for my fork. I think that's just how it has to be though, right? Each user needs their own key, I had it set locally, but not on GitHub for CI initiated by the PR. The tests should pass just fine once merged here.

**Comment by rory-linehan** [comment]
Agreed, I tested your fork locally and checked the docs to make sure that's what was happening. Everything looks good to me!

**Pull request merged**
